### ISSUE TITLE
Windows 10: Installing fortran compiler

### ISSUE THREAD

**Issue by edumur** [Nicholaswogan/NumbaMinpack#2]
Hi,

I tried to install your wonderful package but failed several times.
I guess I didn't install correctly the fortran compiler but my issue here is that I have no idea how to it.
I googled it and install 2~3 things but the installation always failed:
```bash
 python -m pip install NumbaMinpack
Collecting NumbaMinpack
  Using cached NumbaMinpack-0.1.3.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\ed261978\anaconda3\envs\python38\lib\site-packages (from NumbaMinpack) (1.20.3)
Requirement already satisfied: numba in c:\users\ed261978\anaconda3\envs\python38\lib\site-packages (from NumbaMinpack) (0.54.1)
Requirement already satisfied: llvmlite<0.38,>=0.37.0rc1 in c:\users\ed261978\anaconda3\envs\python38\lib\site-packages (from numba->NumbaMinpack) (0.37.0)
Requirement already satisfied: setuptools in c:\users\ed261978\anaconda3\envs\python38\lib\site-packages (from numba->NumbaMinpack) (58.4.0)
Building wheels for collected packages: NumbaMinpack
  Building wheel for NumbaMinpack (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for NumbaMinpack (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      C:\Users\ed261978\AppData\Local\Temp\pip-build-env-hgh86ys7\overlay\Lib\site-packages\setuptools\dist.py:738: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
        File "C:\Users\ed261978\AppData\Local\Temp\pip-build-env-hgh86ys7\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 566, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "C:\Users\ed261978\AppData\Local\Temp\pip-build-env-hgh86ys7\overlay\Lib\site-packages\skbuild\cmaker.py", line 133, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "C:\Users\ed261978\AppData\Local\Temp\pip-build-env-hgh86ys7\overlay\Lib\site-packages\skbuild\cmaker.py", line 88, in get_cmake_version
          raise SKBuildError(
      Traceback (most recent call last):

      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for NumbaMinpack
Failed to build NumbaMinpack
ERROR: Could not build wheels for NumbaMinpack, which is required to install pyproject.toml-based projects
```

Maybe related:
Everytime I was running the pip install, my antivirus pop-up the following alert:
![image](https://user-images.githubusercontent.com/13218882/158633553-b5ec56dc-c044-4649-bc06-fd656096fb51.png)

![image](https://user-images.githubusercontent.com/13218882/158634319-d57e9be3-6547-4890-bd69-d0757ba1216f.png)

Do you have any idea to help me here?

Thanks!

**Comment by Nicholaswogan** [comment]
It looks like your cmake installation is the issue. I'm assuming the issue arise from your antivirus software being too restrictive. Maybe this would be solved by adjusting the settings in your antivirus software

**Comment by edumur** [comment]
Sure:

```bash
Using pip 22.0.4 from C:\Users\ed261978\Anaconda3\envs\python38\lib\site-packages\pip (python 3.8)
Collecting NumbaMinpack
  Using cached NumbaMinpack-0.1.3.tar.gz (25 kB)
  Installing build dependencies ...   Running command pip subprocess to install build dependencies
  Collecting setuptools>=42
    Downloading setuptools-60.10.0-py3-none-any.whl (1.1 MB)
       ---------------------------------------- 1.1/1.1 MB 13.7 MB/s eta 0:00:00
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting scikit-build
    Using cached scikit_build-0.13.1-py2.py3-none-any.whl (75 kB)
  Collecting cmake>=3.18
    Using cached cmake-3.22.3-py2.py3-none-win_amd64.whl (38.1 MB)
  Collecting ninja
    Using cached ninja-1.10.2.3-py2.py3-none-win_amd64.whl (292 kB)
  Collecting packaging
    Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Collecting distro
    Using cached distro-1.7.0-py3-none-any.whl (20 kB)
  Collecting pyparsing!=3.0.5,>=2.0.2
    Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
  Installing collected packages: ninja, cmake, wheel, setuptools, pyparsing, distro, packaging, scikit-build
  Successfully installed cmake-3.22.3 distro-1.7.0 ninja-1.10.2.3 packaging-21.3 pyparsing-3.0.7 scikit-build-0.13.1 setuptools-60.10.0 wheel-0.37.1
done
  Getting requirements to build wheel ...   Running command Getting requirements to build wheel
  running egg_info
  creating NumbaMinpack.egg-info
  writing NumbaMinpack.egg-info\PKG-INFO
  writing dependency_links to NumbaMinpack.egg-info\dependency_links.txt
  writing requirements to NumbaMinpack.egg-info\requires.txt
  writing top-level names to NumbaMinpack.egg-info\top_level.txt
  writing manifest file 'NumbaMinpack.egg-info\SOURCES.txt'
  reading manifest file 'NumbaMinpack.egg-info\SOURCES.txt'
  adding license file 'LICENSE.txt'
  writing manifest file 'NumbaMinpack.egg-info\SOURCES.txt'
  C:\Users\ed261978\AppData\Local\Temp\pip-build-env-cr0e8uk9\overlay\Lib\site-packages\setuptools\dist.py:739: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
done
  Preparing metadata (pyproject.toml) ...   Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating C:\Users\ed261978\AppData\Local\Temp\pip-modern-metadata-bfxhkm7u\NumbaMinpack.egg-info
  writing C:\Users\ed261978\AppData\Local\Temp\pip-modern-metadata-bfxhkm7u\NumbaMinpack.egg-info\PKG-INFO
  writing dependency_links to C:\Users\ed261978\AppData\Local\Temp\pip-modern-metadata-bfxhkm7u\NumbaMinpack.egg-info\dependency_links.txt
  writing requirements to C:\Users\ed261978\AppData\Local\Temp\pip-modern-metadata-bfxhkm7u\NumbaMinpack.egg-info\requires.txt
  writing top-level names to C:\Users\ed261978\AppData\Local\Temp\pip-modern-metadata-bfxhkm7u\NumbaMinpack.egg-info\top_level.txt
  writing manifest file 'C:\Users\ed261978\AppData\Local\Temp\pip-modern-metadata-bfxhkm7u\NumbaMinpack.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\ed261978\AppData\Local\Temp\pip-modern-metadata-bfxhkm7u\NumbaMinpack.egg-info\SOURCES.txt'
  adding license file 'LICENSE.txt'
  writing manifest file 'C:\Users\ed261978\AppData\Local\Temp\pip-modern-metadata-bfxhkm7u\NumbaMinpack.egg-info\SOURCES.txt'
  creating 'C:\Users\ed261978\AppData\Local\Temp\pip-modern-metadata-bfxhkm7u\NumbaMinpack.dist-info'
  C:\Users\ed261978\AppData\Local\Temp\pip-build-env-cr0e8uk9\overlay\Lib\site-packages\setuptools\dist.py:739: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
done
Requirement already satisfied: numba in c:\users\ed261978\anaconda3\envs\python38\lib\site-packages (from NumbaMinpack) (0.54.1)
Requirement already satisfied: numpy in c:\users\ed261978\anaconda3\envs\python38\lib\site-packages (from NumbaMinpack) (1.20.3)
Requirement already satisfied: llvmlite<0.38,>=0.37.0rc1 in c:\users\ed261978\anaconda3\envs\python38\lib\site-packages (from numba->NumbaMinpack) (0.37.0)
Requirement already satisfied: setuptools in c:\users\ed261978\anaconda3\envs\python38\lib\site-packages (from numba->NumbaMinpack) (58.4.0)
Building wheels for collected packages: NumbaMinpack
  Building wheel for NumbaMinpack (pyproject.toml) ...   Running command Building wheel for NumbaMinpack (pyproject.toml)
  C:\Users\ed261978\AppData\Local\Temp\pip-build-env-cr0e8uk9\overlay\Lib\site-packages\setuptools\dist.py:739: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
    File "C:\Users\ed261978\AppData\Local\Temp\pip-build-env-cr0e8uk9\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 566, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "C:\Users\ed261978\AppData\Local\Temp\pip-build-env-cr0e8uk9\overlay\Lib\site-packages\skbuild\cmaker.py", line 133, in __init__
      self.cmake_version = get_cmake_version(self.cmake_executable)
    File "C:\Users\ed261978\AppData\Local\Temp\pip-build-env-cr0e8uk9\overlay\Lib\site-packages\skbuild\cmaker.py", line 88, in get_cmake_version
      raise SKBuildError(
  Traceback (most recent call last):

  Problem with the CMake installation, aborting build. CMake executable is cmake
  error: subprocess-exited-with-error

  × Building wheel for NumbaMinpack (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\ed261978\Anaconda3\envs\python38\python.exe' 'C:\Users\ed261978\Anaconda3\envs\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\ed261978\AppData\Local\Temp\tmpvmuncerk'
  cwd: C:\Users\ed261978\AppData\Local\Temp\pip-install-4zkhbotk\numbaminpack_4de469d45d6a40eb8bfbbd1b173a4b8f
error
  ERROR: Failed building wheel for NumbaMinpack
Failed to build NumbaMinpack
ERROR: Could not build wheels for NumbaMinpack, which is required to install pyproject.toml-based projects
```
